version: '3.3'

services:
  app:
    build:
      context: ./front/
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:5173:5173"

  backend:
    build:
      context: ./back/
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
